import React, { useState, useEffect } from 'react';
// Mock API call function
export async function mockApiCall() {
  return new Promise((resolve) => {
    setTimeout(() => {
      const mockData = {
        status: 'success',
        data: [
          {
            id: 370663,
            sis_course_id: null,
            uuid: "WvAHhY5FINzq5IyRIJybGeiXyFkG3SqHUPb7jZY5",
            integration_id: null,
            sis_import_id: 34,
            name: "InstructureCon 2012",
            course_code: "INSTCON12",
            original_name: "InstructureCon-2012-01",
            workflow_state: "available",
            account_id: 81259,
            root_account_id: 81259,
            enrollment_term_id: 34,
            grading_periods: null,
            grading_standard_id: 25,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-01T00:00:00-06:00",
            start_at: "2012-06-01T00:00:00-06:00",
            end_at: "2012-09-01T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 32,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 17,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Come one, come all to InstructureCon 2012!",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Denver",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370664,
            sis_course_id: null,
            uuid: "A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0",
            integration_id: null,
            sis_import_id: 35,
            name: "College Writing",
            course_code: "COLWRIT101",
            original_name: "College-Writing-101",
            workflow_state: "available",
            account_id: 81260,
            root_account_id: 81260,
            enrollment_term_id: 35,
            grading_periods: null,
            grading_standard_id: 26,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-02T00:00:00-06:00",
            start_at: "2012-06-02T00:00:00-06:00",
            end_at: "2012-09-02T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 25,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 10,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Learn the fundamentals of college-level writing.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/New_York",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370665,
            sis_course_id: null,
            uuid: "B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0A1",
            integration_id: null,
            sis_import_id: 36,
            name: "Introduction to Multivariable Calculus",
            course_code: "MATH201",
            original_name: "Multivariable-Calculus-201",
            workflow_state: "available",
            account_id: 81261,
            root_account_id: 81261,
            enrollment_term_id: 36,
            grading_periods: null,
            grading_standard_id: 27,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-03T00:00:00-06:00",
            start_at: "2012-06-03T00:00:00-06:00",
            end_at: "2012-09-03T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 28,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 12,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Explore the concepts of multivariable calculus.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Chicago",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370666,
            sis_course_id: null,
            uuid: "C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0A1B2",
            integration_id: null,
            sis_import_id: 37,
            name: "Introduction to Microeconomics",
            course_code: "ECON101",
            original_name: "Microeconomics-101",
            workflow_state: "available",
            account_id: 81262,
            root_account_id: 81262,
            enrollment_term_id: 37,
            grading_periods: null,
            grading_standard_id: 28,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-04T00:00:00-06:00",
            start_at: "2012-06-04T00:00:00-06:00",
            end_at: "2012-09-04T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 30,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 15,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Understand the basics of microeconomics.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Los_Angeles",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370667,
            sis_course_id: null,
            uuid: "D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0A1B2C3",
            integration_id: null,
            sis_import_id: 38,
            name: "Analytical Physics 1",
            course_code: "PHYS101",
            original_name: "Physics-101",
            workflow_state: "available",
            account_id: 81263,
            root_account_id: 81263,
            enrollment_term_id: 38,
            grading_periods: null,
            grading_standard_id: 29,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-05T00:00:00-06:00",
            start_at: "2012-06-05T00:00:00-06:00",
            end_at: "2012-09-05T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 35,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 20,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Dive into the principles of analytical physics.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Denver",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370668,
            sis_course_id: null,
            uuid: "E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0A1B2C3D4",
            integration_id: null,
            sis_import_id: 39,
            name: "Introduction to Engineering",
            course_code: "ENGR101",
            original_name: "Engineering-101",
            workflow_state: "available",
            account_id: 81264,
            root_account_id: 81264,
            enrollment_term_id: 39,
            grading_periods: null,
            grading_standard_id: 30,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-06T00:00:00-06:00",
            start_at: "2012-06-06T00:00:00-06:00",
            end_at: "2012-09-06T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 40,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 25,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "An introduction to the field of engineering.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Denver",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          },
          {
            id: 370669,
            sis_course_id: null,
            uuid: "F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0A1B2C3D4E5",
            integration_id: null,
            sis_import_id: 40,
            name: "Introduction to Computer Science",
            course_code: "CS101",
            original_name: "Computer-Science-101",
            workflow_state: "available",
            account_id: 81265,
            root_account_id: 81265,
            enrollment_term_id: 40,
            grading_periods: null,
            grading_standard_id: 31,
            grade_passback_setting: "nightly_sync",
            created_at: "2012-05-07T00:00:00-06:00",
            start_at: "2012-06-07T00:00:00-06:00",
            end_at: "2012-09-07T00:00:00-06:00",
            locale: "en",
            enrollments: null,
            total_students: 45,
            calendar: null,
            default_view: "feed",
            syllabus_body: "<p>syllabus html goes here</p>",
            needs_grading_count: 30,
            term: null,
            course_progress: null,
            apply_assignment_group_weights: true,
            permissions: {"create_discussion_topic":true,"create_announcement":true},
            is_public: true,
            is_public_to_auth_users: true,
            public_syllabus: true,
            public_syllabus_to_auth: true,
            public_description: "Learn the basics of computer science.",
            storage_quota_mb: 5,
            storage_quota_used_mb: 5,
            hide_final_grades: false,
            license: "Creative Commons",
            allow_student_assignment_edits: false,
            allow_wiki_comments: false,
            allow_student_forum_attachments: false,
            open_enrollment: true,
            self_enrollment: false,
            restrict_enrollments_to_course_dates: false,
            course_format: "online",
            access_restricted_by_date: false,
            time_zone: "America/Denver",
            blueprint: true,
            blueprint_restrictions: {"content":true,"points":true,"due_dates":false,"availability_dates":false},
            blueprint_restrictions_by_object_type: {"assignment":{"content":true,"points":true},"wiki_page":{"content":true}},
            template: true
          }
        ]
      };
      resolve(mockData);
    }, 1000); // Simulate network delay
  });
}